title: Page

pages:
  template:
    - section_textbox
    - section_gallery
    # - section_portfolio
    - section_clients
    - section_slider
    - section_videobox
    - redirect

fields:
  title: title

  info:
    label: Hint
    type: info
    text: >
      Die Inhalte werden durch die einzelnen Unterseiten definiert.
